### PR TITLE
[DEPR]: Replace deprecated pkg_resources package with importlib_resources

### PR DESCRIPTION
**Pull request by Abdul-Muqadim-Arbisoft**

### CODE REVIEW

**Review by ziafazal — APPROVED** [review]
👍

**Comment by ziafazal** [comment]
@Abdul-Muqadim-Arbisoft why end to end tests are failing?

**Comment by Abdul-Muqadim-Arbisoft** [comment]
> @Abdul-Muqadim-Arbisoft why end to end tests are failing?

Some depreciated libraries xblock.fragment and xblockutils  and missing dependency importlib-resources issues causing internal server error, which are now resolved

**Review by ziafazal — APPROVED** [review]
👍

**Pull request merged**
